### PR TITLE
Feature/milestone#1

### PR DESCRIPTION
**Pull request by maosan132**
- Files and folders of the project setup
- Ruby script executable from the command line

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @maosan132, 👋 

### Great job thus far! 🙌 Just one more thing. 👇 

- [ ] Set up the linter appropriately. It should be similar to the image below when properly set up. Check [here](https://github.com/microverseinc/linters-config/tree/master/ruby) on how to go about it.

Screenshot 2020-05-15 at 10 46 53

**Kindly submit another CRR once this issue has been addressed.** _Happy coding!_ 🎉

**Comment by maosan132** [comment]
Issue here: stickler warns about main.rb not being executable file. I am using windows10. when run `./main.rb` returns "`hello!`", when run `ls -l main.rb` returns `-rwxr-xr-x`, when run `File.stat('./main.rb').executable?` returns `false`. Huge blockage here, help!!

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @maosan132, 👋 

### Ensure all linter checks passed as in the image in the previous review before submitting for another code review. 💯 

_Happy coding!_ 🎉

**Comment by suretrust** [comment]
> Issue here: stickler warns about main.rb not being executable file. I am using windows10. when run `./main.rb` returns "`hello!`", when run `ls -l main.rb` returns `-rwxr-xr-x`, when run `File.stat('./main.rb').executable?` returns `false`. Huge blockage here, help!!

You could try [this](https://github.com/rubocop-hq/rubocop/issues/4526) or [read more here](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/).

**Review by Forison — APPROVED** [review]
## status approved✔️
# 👋  Mauricio 
## Thank you for addressing the issue with the linters
# See you in the next milestone✈️
#### Happy coding⌨️
Addo

**Pull request merged**
